#use none for production
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.password=admin
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/MaridOne

jwt.secret=DBJLzOFR+2X80I/8vtaH22D/0Tldy0qU1KlxXLYDiwA=

default.url=http://localhost:5173