spring.application.name = MaridOne
spring.devtools.restart.enabled=false

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name = org.postgresql.Driver

spring.profiles.active = dev

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=${DB_URL}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

default.url=${URL_HOST}