CREATE TABLE employee (
    emp_id                BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name            VARCHAR(30)     NOT NULL,
    middle_name           VARCHAR(30),
    last_name             VARCHAR(30)     NOT NULL,
    birth_date            DATE            NOT NULL,
    employment_date_start DATE            NOT NULL,
    employment_date_end   DATE,
    yearly_salary         NUMERIC(38, 2)  NOT NULL,
    email                 VARCHAR(254)    NOT NULL,
    phone_number          VARCHAR(255)    NOT NULL,
    employment_status     VARCHAR(255)    NOT NULL,
    exemption_status      VARCHAR(255)    NOT NULL,
    position              VARCHAR(255)    NOT NULL,
    permanent_address     VARCHAR(255),
    temporary_address     VARCHAR(255),
    city                  VARCHAR(255),
    state                 VARCHAR(255),
    country               VARCHAR(255),
    zip_code              VARCHAR(255),
    manager_id            BIGINT

    CONSTRAINT employee_employment_status_check CHECK (employment_status IN ('REGULAR', 'NEW_HIRE', 'PART_TIME', 'TERMINATED', 'SUSPENDED')),
    CONSTRAINT employee_exemption_status_check  CHECK (exemption_status  IN ('EXEMPT', 'NON_EXEMPT')),
    CONSTRAINT employee_position_check          CHECK (position          IN ('MANAGEMENT', 'HR', 'ACCOUNTING', 'EMPLOYEE', 'MANAGER', 'UNKNOWN')),
    CONSTRAINT fk_employee_manager FOREIGN KEY (manager_id) REFERENCES Employee(emp_id)

);
