CREATE TABLE activity_log (
    activity_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(255)    NOT NULL,
    activity_type   VARCHAR(255)    NOT NULL,
    message         VARCHAR(255)    NOT NULL,
    timestamp       TIMESTAMPTZ     NOT NULL,

    CONSTRAINT activity_log_activity_type_check CHECK (activity_type IN ('LOG', 'READ', 'MODIFY', 'CREATE', 'DELETE', 'UNKNOWN', 'SYSTEM'))
);
