CREATE TABLE bank_account (
    bank_id         BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number  VARCHAR(255)    NOT NULL,
    bank_name       VARCHAR(255)    NOT NULL,
    is_active       BOOLEAN         NOT NULL,
    emp_id          BIGINT,

    CONSTRAINT fk_bank_account_employee FOREIGN KEY (emp_id) REFERENCES employee (emp_id)
);
