CREATE TABLE company_calendar (
    calendar_id BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)    NOT NULL,
    start_date  TIMESTAMPTZ     NOT NULL,
    end_date    TIMESTAMPTZ     NOT NULL,
    is_active   BOOLEAN         NOT NULL
);
