CREATE TABLE template_shift_schedule (
    shift_id    BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time  TIME            NOT NULL,
    end_time    TIME            NOT NULL,
    day_of_week VARCHAR(255)    NOT NULL,
    emp_id      BIGINT,

    CONSTRAINT template_shift_schedule_day_of_week_check CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    CONSTRAINT fk_template_shift_schedule_employee FOREIGN KEY (emp_id) REFERENCES employee (emp_id)
);
