CREATE TABLE daily_shift_schedule (
    daily_shift_id  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date_time TIMESTAMP   NOT NULL,
    end_date_time   TIMESTAMP   NOT NULL,
    shift_id        BIGINT,

    CONSTRAINT fk_daily_shift_schedule_template FOREIGN KEY (shift_id) REFERENCES template_shift_schedule (shift_id)
);
