CREATE TABLE shift_schedule (
    shift_id    BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time  TIME            NOT NULL,
    end_time    TIME            NOT NULL,
    day_of_week VARCHAR(255)    NOT NULL,
    shift_type  VARCHAR(255)    NOT NULL,
    emp_id      BIGINT,

    CONSTRAINT shift_schedule_day_of_week_check CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    CONSTRAINT shift_schedule_shift_type_check  CHECK (shift_type  IN ('BASIC', 'OVERTIME', 'DOUBLE_OVERTIME', 'TRIPLE_OVERTIME', 'HOLIDAY', 'ALLOWANCE', 'NIGHTDIFF', 'FIXED')),
    CONSTRAINT fk_shift_schedule_employee FOREIGN KEY (emp_id) REFERENCES employee (emp_id)
);
