CREATE TABLE payroll_run (
    pay_id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start        DATE            NOT NULL,
    period_end          DATE            NOT NULL,
    period_description  VARCHAR(255),
    payroll_status      VARCHAR(255)    NOT NULL,
    run_type            VARCHAR(255)    NOT NULL,

    CONSTRAINT payroll_run_payroll_status_check CHECK (payroll_status IN ('IN_PROGRESS', 'POSTED')),
    CONSTRAINT payroll_run_run_type_check       CHECK (run_type       IN ('REGULAR', 'ADJUSTMENT'))
);
