CREATE TABLE payroll_item (
    item_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gross_pay   NUMERIC(38, 2)  NOT NULL,
    net_pay     NUMERIC(38, 2)  NOT NULL,
    emp_id      BIGINT          NOT NULL,
    pay_id      BIGINT          NOT NULL,

    CONSTRAINT fk_payroll_item_employee    FOREIGN KEY (emp_id) REFERENCES employee    (emp_id),
    CONSTRAINT fk_payroll_item_payroll_run FOREIGN KEY (pay_id) REFERENCES payroll_run (pay_id)
);
