CREATE TABLE overtime_request (
    overtime_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_status  VARCHAR(255)    NOT NULL,
    request_at      TIMESTAMPTZ     NOT NULL,
    work_date       DATE            NOT NULL,
    start_time      TIMESTAMP       NOT NULL,
    end_time        TIMESTAMP       NOT NULL,
    overtime_type   VARCHAR(255)    NOT NULL,
    reason          VARCHAR(255)    NOT NULL,
    approver        VARCHAR(255),
    approved_at     TIMESTAMPTZ,
    approve_reason  VARCHAR(255),
    emp_id          BIGINT,

    CONSTRAINT overtime_request_request_status_check CHECK (request_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT overtime_request_overtime_type_check  CHECK (overtime_type  IN ('BASIC', 'OVERTIME', 'DOUBLE_OVERTIME', 'TRIPLE_OVERTIME', 'HOLIDAY', 'ALLOWANCE', 'NIGHTDIFF', 'FIXED')),
    CONSTRAINT fk_overtime_request_employee FOREIGN KEY (emp_id) REFERENCES employee (emp_id)
);
