CREATE TABLE earnings_line (
    earnings_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount          NUMERIC(38, 2)  NOT NULL,
    earnings_date   DATE            NOT NULL,
    hours           NUMERIC(38, 2),
    rate            NUMERIC(38, 2),
    is_overtime     BOOLEAN         NOT NULL,
    item_id         BIGINT          NOT NULL,
    earnings_line   BIGINT          UNIQUE,

    CONSTRAINT fk_earnings_line_payroll_item     FOREIGN KEY (item_id)       REFERENCES payroll_item     (item_id),
    CONSTRAINT fk_earnings_line_overtime_request FOREIGN KEY (earnings_line) REFERENCES overtime_request (overtime_id)
);
