CREATE TABLE deductions_line (
    deductions_id   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount          NUMERIC(38, 2)  NOT NULL,
    deduction_type  VARCHAR(255)    NOT NULL,
    item_id         BIGINT          NOT NULL,

    CONSTRAINT deductions_line_deduction_type_check CHECK (deduction_type IN (
        'PAGIBIG', 'SSS', 'PHILHEALTH',
        'BRACKET_LEVEL_ONE', 'BRACKET_LEVEL_TWO', 'BRACKET_LEVEL_THREE',
        'BRACKET_LEVEL_FOUR', 'BRACKET_LEVEL_FIVE', 'BRACKET_LEVEL_SIX',
        'SSS_LOAN', 'PAGIBIG_LOAN', 'CASH_ADVANCE', 'LATE_PENALTY',
        'ABSENT_DEDUCTION', 'EQUIPMENT_LOSS_PENALTY', 'HMO_UPGRADE'
    )),
    CONSTRAINT fk_deductions_line_payroll_item FOREIGN KEY (item_id) REFERENCES payroll_item (item_id)
);
