CREATE TABLE dispute_request (
    dispute_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject         VARCHAR(255)    NOT NULL,
    reason          VARCHAR(255)    NOT NULL,
    status          VARCHAR(255)    NOT NULL,
    status_reason   VARCHAR(255),
    created_at      TIMESTAMPTZ     NOT NULL,
    updated_at      TIMESTAMPTZ,
    item_id         BIGINT          NOT NULL,

    CONSTRAINT dispute_request_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT fk_dispute_request_payroll_item FOREIGN KEY (item_id) REFERENCES payroll_item (item_id)
);
