CREATE TABLE leave_request (
    request_id      BIGINT                              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date_time TIMESTAMP WITHOUT TIME ZONE         NOT NULL,
    end_date_time   TIMESTAMP WITHOUT TIME ZONE         NOT NULL,
    request_status  VARCHAR(255)                        NOT NULL,
    reason          VARCHAR(255)                        NOT NULL,
    approver        VARCHAR(255),
    approver_reason VARCHAR(255),
    emp_id          BIGINT                              NOT NULL,

    CONSTRAINT chk_valid_dates CHECK (end_date_time > start_date_time),
    CONSTRAINT leave_request_request_status_check CHECK (request_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT fk_leave_request_employee FOREIGN KEY (emp_id) REFERENCES employee (emp_id)
);
