CREATE TABLE leave_balance (
    leave_id        BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_hours   NUMERIC(38, 2)  NOT NULL,
    leave_type      VARCHAR(255)    NOT NULL,
    emp_id          BIGINT          NOT NULL,

    CONSTRAINT leave_balance_leave_type_check CHECK (leave_type IN (
        'VACATION_LEAVE', 'SICK_LEAVE', 'MATERNITY_LEAVE',
        'PATERNITY_LEAVE', 'SOLO_PARENT_LEAVE', 'MAGNA_CARTA', 'RA9262'
    )),
    CONSTRAINT fk_leave_balance_employee FOREIGN KEY (emp_id) REFERENCES employee (emp_id)
);
