CREATE TABLE attendance_log (
    attendance_id   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp       TIMESTAMPTZ     NOT NULL,
    direction       VARCHAR(255)    NOT NULL,
    emp_id          BIGINT          NOT NULL,

    CONSTRAINT fk_attendance_log_employee FOREIGN KEY (emp_id) REFERENCES employee (emp_id)
);
