CREATE TABLE notification (
    notification_id BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message         VARCHAR(255)    NOT NULL,
    importance      VARCHAR(255)    NOT NULL,
    read_status     BOOLEAN         NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL,
    employee_id     BIGINT          NOT NULL,

    CONSTRAINT fk_notification_employee FOREIGN KEY (employee_id) REFERENCES employee (emp_id)
);
