CREATE TABLE document_path (
    path_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name   VARCHAR(255)    NOT NULL,
    file_path   VARCHAR(255)    NOT NULL,
    file_type   VARCHAR(255)    NOT NULL,
    username    VARCHAR(255)    NOT NULL,

    CONSTRAINT fk_document_path_user_account FOREIGN KEY (username) REFERENCES user_account (username)
);
